version: '3'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prisma
    ports:
      - '5432:5432'
  adminer:
    image: adminer:4.7.9
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres: ~
